"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FileText, Download, Mail, Share2, AlertTriangle, CheckCircle, XCircle, BarChart3 } from "lucide-react"

interface BiasReport {
  id: string
  title: string
  date: string
  overallScore: number
  issues: number
  status: "completed" | "in-progress" | "draft"
  categories: {
    occupationGap: number
    agencyGap: number
    appearanceFocus: number
    relationshipDefining: number
  }
}

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState<string | null>(null)

  const reports: BiasReport[] = [
    {
      id: "1",
      title: "Kaho Naa... Pyaar Hai - Script Analysis",
      date: "2024-01-15",
      overallScore: 72,
      issues: 8,
      status: "completed",
      categories: {
        occupationGap: 85,
        agencyGap: 65,
        appearanceFocus: 70,
        relationshipDefining: 68,
      },
    },
    {
      id: "2",
      title: "Dilwale Dulhania Le Jayenge - Comprehensive Review",
      date: "2024-01-12",
      overallScore: 69,
      issues: 12,
      status: "completed",
      categories: {
        occupationGap: 78,
        agencyGap: 72,
        appearanceFocus: 65,
        relationshipDefining: 71,
      },
    },
    {
      id: "3",
      title: "Queen - Progressive Analysis",
      date: "2024-01-10",
      overallScore: 34,
      issues: 3,
      status: "completed",
      categories: {
        occupationGap: 25,
        agencyGap: 30,
        appearanceFocus: 40,
        relationshipDefining: 42,
      },
    },
  ]

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "completed":
        return <CheckCircle className="h-4 w-4 text-green-600" />
      case "in-progress":
        return <AlertTriangle className="h-4 w-4 text-yellow-600" />
      case "draft":
        return <XCircle className="h-4 w-4 text-gray-600" />
      default:
        return null
    }
  }

  const getScoreColor = (score: number) => {
    if (score > 70) return "text-red-600"
    if (score > 50) return "text-yellow-600"
    return "text-green-600"
  }

  const generateSampleReport = async () => {
    try {
      // Create a sample PDF blob
      const reportContent = `
GENDER BIAS ANALYSIS REPORT
==========================

Movie: Sample Analysis Report
Generated: ${new Date().toLocaleDateString()}

OVERALL BIAS SCORE: 65/100
Bias Level: Medium - Moderate bias present

DETAILED ANALYSIS:
- Occupation Gap: 70/100
- Agency Gap: 60/100  
- Appearance Focus: 55/100
- Relationship Defining: 75/100

RECOMMENDATIONS:
• Add professional identities to female characters
• Give female characters more decision-making roles
• Reduce emphasis on physical appearance
• Balance dialogue distribution between genders

Report generated by Bollywood Bias Buster
    `

      const blob = new Blob([reportContent], { type: "text/plain" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = "bias_analysis_report.txt"
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error("Error generating report:", error)
      alert("Error generating report. Please try again.")
    }
  }

  const downloadPDF = async () => {
    if (!selectedReport) return

    try {
      const report = reports.find((r) => r.id === selectedReport)
      if (!report) return

      // Create PDF content
      const pdfContent = `
GENDER BIAS ANALYSIS REPORT
==========================

Movie: ${report.title}
Date: ${report.date}
Overall Score: ${report.overallScore}/100

BIAS BREAKDOWN:
- Occupation Gap: ${report.categories.occupationGap}%
- Agency Gap: ${report.categories.agencyGap}%
- Appearance Focus: ${report.categories.appearanceFocus}%
- Relationship Defining: ${report.categories.relationshipDefining}%

Issues Identified: ${report.issues}
Status: ${report.status}

RECOMMENDATIONS:
• Add professional identities to female characters beyond family relationships
• Give female characters more decision-making roles and active agency
• Reduce emphasis on physical appearance in character descriptions
• Balance dialogue distribution between male and female characters

Generated by Bollywood Bias Buster
    `

      const blob = new Blob([pdfContent], { type: "application/pdf" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${report.title.replace(/[^a-zA-Z0-9]/g, "_")}_bias_report.pdf`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error("Error downloading PDF:", error)
      alert("Error downloading PDF. Please try again.")
    }
  }

  const emailReport = async () => {
    if (!selectedReport) return

    const report = reports.find((r) => r.id === selectedReport)
    if (!report) return

    const subject = encodeURIComponent(`Gender Bias Analysis Report - ${report.title}`)
    const body = encodeURIComponent(`
Hi,

Please find the gender bias analysis report for "${report.title}":

Overall Bias Score: ${report.overallScore}/100
Issues Identified: ${report.issues}

Key Findings:
- Occupation Gap: ${report.categories.occupationGap}%
- Agency Gap: ${report.categories.agencyGap}%
- Appearance Focus: ${report.categories.appearanceFocus}%
- Relationship Defining: ${report.categories.relationshipDefining}%

This report was generated using Bollywood Bias Buster.

Best regards
  `)

    window.open(`mailto:?subject=${subject}&body=${body}`)
  }

  const shareReport = async () => {
    if (!selectedReport) return

    const report = reports.find((r) => r.id === selectedReport)
    if (!report) return

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Gender Bias Analysis - ${report.title}`,
          text: `Check out this gender bias analysis report for "${report.title}". Overall bias score: ${report.overallScore}/100`,
          url: window.location.href,
        })
      } catch (error) {
        console.error("Error sharing:", error)
        copyToClipboard()
      }
    } else {
      copyToClipboard()
    }
  }

  const copyToClipboard = () => {
    const report = reports.find((r) => r.id === selectedReport)
    if (!report) return

    const shareText = `Gender Bias Analysis Report - ${report.title}
Overall Score: ${report.overallScore}/100
Generated by Bollywood Bias Buster
${window.location.href}`

    navigator.clipboard
      .writeText(shareText)
      .then(() => {
        alert("Report link copied to clipboard!")
      })
      .catch(() => {
        alert("Unable to copy to clipboard. Please copy the URL manually.")
      })
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Bias Reports</h1>
          <p className="text-gray-600">
            Comprehensive feedback reports for filmmakers to address gender bias in their projects.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Reports List */}
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  Generated Reports
                </CardTitle>
                <CardDescription>Click on a report to view details</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {reports.map((report) => (
                  <div
                    key={report.id}
                    className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                      selectedReport === report.id
                        ? "border-blue-500 bg-blue-50"
                        : "border-gray-200 hover:border-gray-300"
                    }`}
                    onClick={() => setSelectedReport(report.id)}
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        {getStatusIcon(report.status)}
                        <Badge variant="outline" className={getScoreColor(report.overallScore)}>
                          {report.overallScore}/100
                        </Badge>
                      </div>
                      <div className="text-xs text-gray-500">{report.date}</div>
                    </div>
                    <h4 className="font-medium text-sm mb-1">{report.title}</h4>
                    <div className="text-xs text-gray-600">{report.issues} issues identified</div>
                  </div>
                ))}

                <Button variant="outline" className="w-full bg-transparent" onClick={generateSampleReport}>
                  <FileText className="h-4 w-4 mr-2" />
                  Generate Sample Report
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Report Details */}
          <div className="lg:col-span-2">
            {selectedReport ? (
              <Card>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>{reports.find((r) => r.id === selectedReport)?.title}</CardTitle>
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" onClick={downloadPDF}>
                        <Download className="h-4 w-4 mr-1" />
                        Download PDF
                      </Button>
                      <Button variant="outline" size="sm" onClick={emailReport}>
                        <Mail className="h-4 w-4 mr-1" />
                        Email
                      </Button>
                      <Button variant="outline" size="sm" onClick={shareReport}>
                        <Share2 className="h-4 w-4 mr-1" />
                        Share
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="summary" className="w-full">
                    <TabsList className="grid w-full grid-cols-4">
                      <TabsTrigger value="summary">Summary</TabsTrigger>
                      <TabsTrigger value="issues">Issues</TabsTrigger>
                      <TabsTrigger value="recommendations">Fixes</TabsTrigger>
                      <TabsTrigger value="trends">Trends</TabsTrigger>
                    </TabsList>

                    <TabsContent value="summary" className="space-y-6">
                      {(() => {
                        const report = reports.find((r) => r.id === selectedReport)!
                        return (
                          <>
                            <div className="grid md:grid-cols-2 gap-4">
                              <div className="text-center p-4 bg-gray-50 rounded-lg">
                                <div className={`text-3xl font-bold ${getScoreColor(report.overallScore)}`}>
                                  {report.overallScore}/100
                                </div>
                                <div className="text-sm text-gray-600">Overall Bias Score</div>
                              </div>
                              <div className="text-center p-4 bg-gray-50 rounded-lg">
                                <div className="text-3xl font-bold text-gray-900">{report.issues}</div>
                                <div className="text-sm text-gray-600">Issues Identified</div>
                              </div>
                            </div>

                            <div>
                              <h4 className="font-medium mb-3">Bias Categories Breakdown</h4>
                              <div className="space-y-3">
                                <div>
                                  <div className="flex justify-between text-sm mb-1">
                                    <span>Occupation Gap</span>
                                    <span className={getScoreColor(report.categories.occupationGap)}>
                                      {report.categories.occupationGap}%
                                    </span>
                                  </div>
                                  <Progress value={report.categories.occupationGap} />
                                </div>
                                <div>
                                  <div className="flex justify-between text-sm mb-1">
                                    <span>Agency Gap</span>
                                    <span className={getScoreColor(report.categories.agencyGap)}>
                                      {report.categories.agencyGap}%
                                    </span>
                                  </div>
                                  <Progress value={report.categories.agencyGap} />
                                </div>
                                <div>
                                  <div className="flex justify-between text-sm mb-1">
                                    <span>Appearance Focus</span>
                                    <span className={getScoreColor(report.categories.appearanceFocus)}>
                                      {report.categories.appearanceFocus}%
                                    </span>
                                  </div>
                                  <Progress value={report.categories.appearanceFocus} />
                                </div>
                                <div>
                                  <div className="flex justify-between text-sm mb-1">
                                    <span>Relationship Defining</span>
                                    <span className={getScoreColor(report.categories.relationshipDefining)}>
                                      {report.categories.relationshipDefining}%
                                    </span>
                                  </div>
                                  <Progress value={report.categories.relationshipDefining} />
                                </div>
                              </div>
                            </div>
                          </>
                        )
                      })()}
                    </TabsContent>

                    <TabsContent value="issues" className="space-y-4">
                      <div className="space-y-4">
                        <div className="p-4 border border-red-200 bg-red-50 rounded-lg">
                          <div className="flex items-center gap-2 mb-2">
                            <Badge variant="destructive">High Priority</Badge>
                            <span className="font-medium">Occupation Gap</span>
                          </div>
                          <p className="text-sm text-gray-700 mb-2">
                            Female character introduced only as "daughter of" without professional identity.
                          </p>
                          <div className="text-xs text-gray-600 bg-white p-2 rounded italic">
                            "Sonia Saxena, daughter of Mr Saxena"
                          </div>
                        </div>

                        <div className="p-4 border border-yellow-200 bg-yellow-50 rounded-lg">
                          <div className="flex items-center gap-2 mb-2">
                            <Badge variant="secondary" className="bg-yellow-200 text-yellow-800">
                              Medium Priority
                            </Badge>
                            <span className="font-medium">Agency Imbalance</span>
                          </div>
                          <p className="text-sm text-gray-700 mb-2">
                            Male character shown with active goals and aspirations, female character passive.
                          </p>
                          <div className="text-xs text-gray-600 bg-white p-2 rounded italic">
                            "Rohit is an aspiring singer... Sonia receives a car as birthday present"
                          </div>
                        </div>

                        <div className="p-4 border border-orange-200 bg-orange-50 rounded-lg">
                          <div className="flex items-center gap-2 mb-2">
                            <Badge variant="outline" className="border-orange-300 text-orange-700">
                              Low Priority
                            </Badge>
                            <span className="font-medium">Appearance Focus</span>
                          </div>
                          <p className="text-sm text-gray-700 mb-2">
                            Emphasis on physical appearance rather than character traits.
                          </p>
                          <div className="text-xs text-gray-600 bg-white p-2 rounded italic">
                            "Sonia is beautiful and comes from a wealthy family"
                          </div>
                        </div>
                      </div>
                    </TabsContent>

                    <TabsContent value="recommendations" className="space-y-4">
                      <div className="space-y-4">
                        <div className="p-4 border border-green-200 bg-green-50 rounded-lg">
                          <h4 className="font-medium text-green-800 mb-2">Recommended Fix #1</h4>
                          <p className="text-sm text-gray-700 mb-2">
                            Add professional identity to female character introduction:
                          </p>
                          <div className="text-sm bg-white p-3 rounded border">
                            <div className="text-red-600 mb-2">
                              <strong>Before:</strong> "Sonia Saxena, daughter of Mr Saxena"
                            </div>
                            <div className="text-green-600">
                              <strong>After:</strong> "Sonia Saxena, a marketing executive and daughter of Mr Saxena"
                            </div>
                          </div>
                          <div className="text-xs text-green-700 mt-2">
                            <strong>Impact:</strong> Reduces occupation gap bias by 65%
                          </div>
                        </div>

                        <div className="p-4 border border-green-200 bg-green-50 rounded-lg">
                          <h4 className="font-medium text-green-800 mb-2">Recommended Fix #2</h4>
                          <p className="text-sm text-gray-700 mb-2">Balance character agency and aspirations:</p>
                          <div className="text-sm bg-white p-3 rounded border">
                            <div className="text-green-600">
                              <strong>Addition:</strong> "Both share dreams of making their mark in their respective
                              fields"
                            </div>
                          </div>
                          <div className="text-xs text-green-700 mt-2">
                            <strong>Impact:</strong> Improves agency balance by 45%
                          </div>
                        </div>

                        <div className="p-4 border border-blue-200 bg-blue-50 rounded-lg">
                          <h4 className="font-medium text-blue-800 mb-2">Alternative Approach</h4>
                          <p className="text-sm text-gray-700 mb-2">Complete rewrite maintaining narrative flow:</p>
                          <div className="text-sm bg-white p-3 rounded border italic">
                            "When car salesman and aspiring singer Rohit delivers a birthday present to Sonia Saxena, a
                            finance professional, their chance encounter sparks an unexpected connection between two
                            ambitious individuals."
                          </div>
                          <div className="text-xs text-blue-700 mt-2">
                            <strong>Impact:</strong> Overall bias reduction of 72%
                          </div>
                        </div>
                      </div>
                    </TabsContent>

                    <TabsContent value="trends" className="space-y-4">
                      <div className="text-center py-8 text-gray-500">
                        <BarChart3 className="h-12 w-12 mx-auto mb-4" />
                        <p>
                          Trend analysis would show bias patterns across similar films, directors, and time periods.
                        </p>
                        <p className="text-sm mt-2">This feature compares current script against historical data.</p>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
            ) : (
              <Card>
                <CardContent className="text-center py-12">
                  <FileText className="h-12 w-12 mx-auto mb-4 text-gray-400" />
                  <h3 className="text-lg font-medium text-gray-900 mb-2">Select a Report</h3>
                  <p className="text-gray-600">
                    Choose a report from the list to view detailed analysis and recommendations.
                  </p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
